# Generated by Django 3.2.17 on 2023-02-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('Vehicle Diagnostics', 'Vehicle Diagnostics'), ('Start and charging system repairs', 'Start and charging system repairs'), ('Replacement of light bulbs', 'Replacement of light bulbs'), ('AC service', 'AC service'), ('Clutch replacement', 'Clutch replacement'), ('Cambelt repair', 'Cambelt repair'), ('Basic service', 'Basic service'), ('Big service', 'Big service'), ('Electronic systems repair', 'Electronic systems repair'), ('Tire change and repair', 'Tire change and repair')], default='', max_length=50),
        ),
    ]
